let negativeInteger = -10
    zeroInteger = 0,
    positiveInteger = 42,
    negativeDecimal = -16.84,
    zeroDecimal = 0.0,
    positiveDecimal = 420.69,
    singleQuote = 'A string between single quotes',
    doubleQuote = "A string between double quotes",
    backtick = `A string between backticks`,
    trueBool = true,
    falseBool = false,
    undefinedVariable = undefined,
    emptyVariable = null